services:

  mysqldb:
    image: mysql:8.0.13
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservations

  spring-mysql-docker:
    container_name: app_spring
    image: marko30/reserve-your-spot:latest
    ports:
      - "9090:8080"
    restart: on-failure
    environment:
        MYSQL_HOST: mysqldb
        MYSQL_USER: root
        MYSQL_PASSWORD: root


