apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  mysql-server:  mysqldb    # The name of mysql service
  mysql-database-name: reservations     # The name of the database used by the demo app
  mysql-user-username: root   # A new created user for the demo app